---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
            args: [--remove]
          - id: check-yaml
          - id: debug-statements
            language_version: python3
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            language_version: python3
            additional_dependencies: [flake8-typing-imports==1.9.0]
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.7
      hooks:
          - id: autopep8
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
      - id: isort
        args: [--filter-files]
        files: \.py$
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.2.1
      hooks:
          - id: add-trailing-comma
            # Should be activated if we are Python 3 only. PY3
            # args: [--py36-plus]
    - repo: local
      hooks:
          - id: rst
            name: rst
            entry: rst-lint --encoding utf-8
            files: .rst
            language: python
            additional_dependencies: [pygments, restructuredtext_lint]
